"""empty message

Revision ID: 19b1fe775d56
Revises: 59c4f41a2fc0
Create Date: 2025-07-29 17:25:26.574917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b1fe775d56'
down_revision = '59c4f41a2fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'bookings_hut_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], [
                                    'id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'bookings_hut_id_fkey'), 'hut', ['hut_id'], ['id'])

    # ### end Alembic commands ###
