"""empty message

Revision ID: 1d45d404826d
Revises: 39321fefb46f
Create Date: 2025-07-22 22:22:48.761944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d45d404826d'
down_revision = '39321fefb46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('special_requests',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('transaction_payment',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status_payment',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status_payment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('transaction_payment',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('special_requests',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
