"""empty message

Revision ID: 2b085ec90095
Revises: facf832fb501
Create Date: 2025-07-31 00:19:10.710966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b085ec90095'
down_revision = 'facf832fb501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('special_requests',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('transaction_payment',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status_payment',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status_payment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('transaction_payment',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('special_requests',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
