"""empty message

Revision ID: 391a16d80dda
Revises: d6dc31764835
Create Date: 2025-07-20 22:29:30.584597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391a16d80dda'
down_revision = 'd6dc31764835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('huts_image_url_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('huts_image_url_key'), ['image_url'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
