"""empty message

Revision ID: 4a2efa711b2f
Revises: 19b1fe775d56
Create Date: 2025-07-29 17:31:12.257865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2efa711b2f'
down_revision = '19b1fe775d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hut_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'hut_favorites_hut_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f(
            'hut_favorites_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], [
                                    'id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], [
                                    'id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hut_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'hut_favorites_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f(
            'hut_favorites_hut_id_fkey'), 'hut', ['hut_id'], ['id'])

    # ### end Alembic commands ###
