"""empty message

Revision ID: 59c4f41a2fc0
Revises: 7c8b1d91c18d
Create Date: 2025-07-29 17:20:10.319718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c4f41a2fc0'
down_revision = '7c8b1d91c18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hut_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'hut_favorites_hut_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], ['id'])

    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'huts_album_hut_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('huts_album_hut_id_fkey'), 'hut', [
                                    'hut_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hut_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hut_favorites_hut_id_fkey'), 'hut', [
                                    'hut_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
