"""empty message

Revision ID: 71dde4f66445
Revises: 56e7628057f9
Create Date: 2025-07-22 19:33:17.172308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dde4f66445'
down_revision = '56e7628057f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('location_address_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('location_city_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('location_complex_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('location_latitude_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('location_longitude_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('location_region_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('location_region_key'), ['region'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('location_longitude_key'), ['longitude'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('location_latitude_key'), ['latitude'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('location_complex_key'), ['complex'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('location_city_key'), ['city'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('location_address_key'), ['address'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
