"""empty message

Revision ID: 794eaced17b4
Revises: 7ed2073dd9c3
Create Date: 2025-07-22 19:34:00.796239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794eaced17b4'
down_revision = '7ed2073dd9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('locations_address_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('locations_city_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('locations_complex_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('locations_latitude_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('locations_longitude_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('locations_region_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('locations_region_key'), ['region'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('locations_longitude_key'), ['longitude'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('locations_latitude_key'), ['latitude'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('locations_complex_key'), ['complex'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('locations_city_key'), ['city'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('locations_address_key'), ['address'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
