"""empty message

Revision ID: d579972de564
Revises: f9c91277d81f
Create Date: 2025-07-23 00:11:26.889443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd579972de564'
down_revision = 'f9c91277d81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('huts_album_image_url_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('huts_album_image_url_key'), ['image_url'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
