"""empty message

Revision ID: f9c91277d81f
Revises: 71dde4f66445
Create Date: 2025-07-23 00:01:22.246926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c91277d81f'
down_revision = '71dde4f66445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('huts_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('huts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('huts_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
