"""empty message

Revision ID: facf832fb501
Revises: 4a2efa711b2f
Create Date: 2025-07-29 17:34:58.279143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facf832fb501'
down_revision = '4a2efa711b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'bookings_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], [
                                    'id'], ondelete='CASCADE')

    with op.batch_alter_table('hut', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'huts_location_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'locations', ['location_id'], [
                                    'id'], ondelete='CASCADE')

    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'huts_album_hut_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], [
                                    'id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'reviews_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f(
            'reviews_hut_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], [
                                    'id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'hut', ['hut_id'], [
                                    'id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'reviews_hut_id_fkey'), 'hut', ['hut_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f(
            'reviews_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('huts_album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'huts_album_hut_id_fkey'), 'hut', ['hut_id'], ['id'])

    with op.batch_alter_table('hut', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'huts_location_id_fkey'), 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f(
            'bookings_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
